<a href="https://colab.research.google.com/github/pablex72/deep-learning-tasks-datitos/blob/main/pytorch_manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [4]:
x.shape

torch.Size([12])

In [5]:
x.numel()

12

In [6]:
X = x.reshape(3,4)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [8]:
X = x.reshape(4,-1)
X

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [9]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [11]:
torch.randn(3,4)

tensor([[ 0.2562, -0.9653, -1.3832,  0.0915],
        [ 2.9005, -1.0564,  0.2126, -0.2508],
        [ 0.5231, -3.1458,  0.2815, -0.5926]])

array de tres dimensiones

In [12]:
torch.tensor([[[2,1,4,3],[1,2,3,4]],[[4,3,2,1],[4,3,2,1]]])

tensor([[[2, 1, 4, 3],
         [1, 2, 3, 4]],

        [[4, 3, 2, 1],
         [4, 3, 2, 1]]])

OPERACIONES

Se haran las operaciones elemento a elemento a no ser que indiquemos que apliquen producto punto

In [14]:
x = torch.tensor([1,2,4,8])
y = torch.tensor([2,2,2,2])
x+y, x-y, x*y, x/y, x**y #The ** operator is exponentiation

torch.dot(x,y)

tensor(30)

In [15]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

BROADCASTING MECHANISM (when shapes differ)

In [16]:
a = torch.arange(3).reshape((3,1)) # dame una arreglo de 3 y reformalo como 3 filas y 1 columnas
b = torch.arange(2).reshape((1,2)) # dame un arreglo de 2 y reformalo como 1 fila y 2 columnas
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [17]:
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [18]:
a + 5

tensor([[5],
        [6],
        [7]])

Indexing and Slicing

(-1), select the last element and [1:3] selsects the second and thrid elements

In [19]:
X[-1], X[1:3]

(tensor([ 9., 10., 11.]), tensor([[3., 4., 5.],
         [6., 7., 8.]]))

In [20]:
X[1,2] = 9
X 

tensor([[ 0.,  1.,  2.],
        [ 3.,  4.,  9.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

In [21]:
X[0:2,:] = 12
X

tensor([[12., 12., 12.],
        [12., 12., 12.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]])

Conversion to other python objects

In [22]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [23]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)